### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by schan219** [xwa130/group-scalability#1]
Set up project with docker:
- frontend: Angular 6
- platform: node.js v8.11.^

**Comment by xwa130** [comment]
@schan219 I'm sorry my slack has some problem, I didn't receive your msg until now, but it looks like I can not send you msg either, and I can not read history... So the only way I can talk with you is here....

what do you mean you can not update? I think you can create branch, can't you? let me know you have problem in creating branches

Also, I realized we can use npm to create a local env rather than to use docker, so if docker is too complicated, please just set up in local, and we could `npm install` everything, lol

**Comment by schan219** [comment]
Okay, I'll do that first.

**Comment by schan219** [comment]
I cannot create a pull request because we have no master branch.
